const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getDashboardSummary: () => ipcRenderer.invoke('db:getDashboardSummary'),
  getReportSummary: (fromDate, toDate) => ipcRenderer.invoke('db:getReportSummary', { fromDate, toDate }),
  getProductPerformance: (fromDate, toDate) => ipcRenderer.invoke('db:getProductPerformance', { fromDate, toDate }),
  getCustomerAnalysis: (fromDate, toDate) => ipcRenderer.invoke('db:getCustomerAnalysis', { fromDate, toDate }),
  getSupplierAnalysis: (fromDate, toDate) => ipcRenderer.invoke('db:getSupplierAnalysis', { fromDate, toDate }),
  getReportStats: (fromDate, toDate) => ipcRenderer.invoke('db:getReportStats', { fromDate, toDate }),
  getSettings: () => ipcRenderer.invoke('db:getSettings'),
  saveSettings: (settings) => ipcRenderer.invoke('db:saveSettings', settings),
  listProducts: () => ipcRenderer.invoke('db:listProducts'),
  saveProduct: (product) => ipcRenderer.invoke('db:saveProduct', product),
  deleteProduct: (id) => ipcRenderer.invoke('db:deleteProduct', id),
  listCustomers: () => ipcRenderer.invoke('db:listCustomers'),
  saveCustomer: (customer) => ipcRenderer.invoke('db:saveCustomer', customer),
  deleteCustomer: (id) => ipcRenderer.invoke('db:deleteCustomer', id),
  listSuppliers: () => ipcRenderer.invoke('db:listSuppliers'),
  saveSupplier: (supplier) => ipcRenderer.invoke('db:saveSupplier', supplier),
  deleteSupplier: (id) => ipcRenderer.invoke('db:deleteSupplier', id),
  listInventory: () => ipcRenderer.invoke('db:listInventory'),
  listSales: () => ipcRenderer.invoke('db:listSales'),
  createSale: (payload) => ipcRenderer.invoke('db:createSale', payload),
  listPurchases: () => ipcRenderer.invoke('db:listPurchases'),
  createPurchase: (payload) => ipcRenderer.invoke('db:createPurchase', payload),
  listOrders: () => ipcRenderer.invoke('db:listOrders'),
  saveOrder: (order) => ipcRenderer.invoke('db:saveOrder', order),
  listExpenses: () => ipcRenderer.invoke('db:listExpenses'),
  saveExpense: (expense) => ipcRenderer.invoke('db:saveExpense', expense),
  chooseBackupPath: () => ipcRenderer.invoke('app:chooseBackupPath'),
  chooseRestorePath: () => ipcRenderer.invoke('app:chooseRestorePath'),
  backupDatabase: (filePath) => ipcRenderer.invoke('db:backupDatabase', filePath),
  restoreDatabase: (filePath) => ipcRenderer.invoke('db:restoreDatabase', filePath)
});
